Name: Product
Host: 0.0.0.0
Port: 8001

ProductRpc:
  Etcd:
    Hosts:
    - etcd:2379
    Key: product.rpc

Telemetry:
  Name: product.api
  Endpoint: jaeger:4317
  Sampler: 1.0
  Batcher: otlpgrpc
Prometheus:
  Host: 0.0.0.0
  Port: 9081
  Path: /metrics
Auth:
  AccessSecret: uOvKLmVfztaXGpNYd4Z0I1SiT7MweJhl
  AccessExpire: 86400
Log:
  ServiceName: api.api
  Mode: file
  Encoding: json
  Path: /var/log/golang
  Level: info
  TimeFormat: "2006-01-02T15:04:05.000Z07:00"
