// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	merchantFieldNames          = builder.RawFieldNames(&Merchant{})
	merchantRows                = strings.Join(merchantFieldNames, ",")
	merchantRowsExpectAutoSet   = strings.Join(stringx.Remove(merchantFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	merchantRowsWithPlaceHolder = strings.Join(stringx.Remove(merchantFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheMerchantIdPrefix              = "cache:merchant:id:"
	cacheMerchantCasdoorClientIdPrefix = "cache:merchant:casdoorClientId:"
	cacheMerchantWxAppIdPrefix         = "cache:merchant:wxAppId:"
)

type (
	merchantModel interface {
		Insert(ctx context.Context, data *Merchant) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Merchant, error)
		FindOneByCasdoorClientId(ctx context.Context, casdoorClientId string) (*Merchant, error)
		FindOneByWxAppId(ctx context.Context, wxAppId string) (*Merchant, error)
		Update(ctx context.Context, data *Merchant) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMerchantModel struct {
		sqlc.CachedConn
		table string
	}

	Merchant struct {
		Id                     int64          `db:"id"`
		Name                   string         `db:"name"`                      // 商户名称
		Status                 int64          `db:"status"`                    // 状态: 1启用 0停用
		CasdoorEndpoint        string         `db:"casdoor_endpoint"`          // 该商户的 Casdoor 实例地址
		CasdoorClientId        string         `db:"casdoor_client_id"`         // 该商户在 Casdoor 的应用 clientId
		CasdoorClientSecretEnc string         `db:"casdoor_client_secret_enc"` // Casdoor 应用 clientSecret（AES-GCM 加密后）
		CasdoorOrg             string         `db:"casdoor_org"`               // Casdoor organization（租户名）
		CasdoorApp             string         `db:"casdoor_app"`               // Casdoor application 名
		CasdoorCertPem         sql.NullString `db:"casdoor_cert_pem"`          // 该商户 Casdoor 应用证书公钥（校验 JWT）
		WxAppId                string         `db:"wx_app_id"`                 // 微信小程序 AppID（公开）
		WxAppSecretEnc         string         `db:"wx_app_secret_enc"`         // 微信 AppSecret（AES-GCM 加密后）
		CreateTime             time.Time      `db:"create_time"`
		UpdateTime             time.Time      `db:"update_time"`
	}
)

func newMerchantModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMerchantModel {
	return &defaultMerchantModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`merchant`",
	}
}

func (m *defaultMerchantModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	merchantCasdoorClientIdKey := fmt.Sprintf("%s%v", cacheMerchantCasdoorClientIdPrefix, data.CasdoorClientId)
	merchantIdKey := fmt.Sprintf("%s%v", cacheMerchantIdPrefix, id)
	merchantWxAppIdKey := fmt.Sprintf("%s%v", cacheMerchantWxAppIdPrefix, data.WxAppId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, merchantCasdoorClientIdKey, merchantIdKey, merchantWxAppIdKey)
	return err
}

func (m *defaultMerchantModel) FindOne(ctx context.Context, id int64) (*Merchant, error) {
	merchantIdKey := fmt.Sprintf("%s%v", cacheMerchantIdPrefix, id)
	var resp Merchant
	err := m.QueryRowCtx(ctx, &resp, merchantIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantModel) FindOneByCasdoorClientId(ctx context.Context, casdoorClientId string) (*Merchant, error) {
	merchantCasdoorClientIdKey := fmt.Sprintf("%s%v", cacheMerchantCasdoorClientIdPrefix, casdoorClientId)
	var resp Merchant
	err := m.QueryRowIndexCtx(ctx, &resp, merchantCasdoorClientIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `casdoor_client_id` = ? limit 1", merchantRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, casdoorClientId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantModel) FindOneByWxAppId(ctx context.Context, wxAppId string) (*Merchant, error) {
	merchantWxAppIdKey := fmt.Sprintf("%s%v", cacheMerchantWxAppIdPrefix, wxAppId)
	var resp Merchant
	err := m.QueryRowIndexCtx(ctx, &resp, merchantWxAppIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `wx_app_id` = ? limit 1", merchantRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, wxAppId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantModel) Insert(ctx context.Context, data *Merchant) (sql.Result, error) {
	merchantCasdoorClientIdKey := fmt.Sprintf("%s%v", cacheMerchantCasdoorClientIdPrefix, data.CasdoorClientId)
	merchantIdKey := fmt.Sprintf("%s%v", cacheMerchantIdPrefix, data.Id)
	merchantWxAppIdKey := fmt.Sprintf("%s%v", cacheMerchantWxAppIdPrefix, data.WxAppId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, merchantRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Status, data.CasdoorEndpoint, data.CasdoorClientId, data.CasdoorClientSecretEnc, data.CasdoorOrg, data.CasdoorApp, data.CasdoorCertPem, data.WxAppId, data.WxAppSecretEnc)
	}, merchantCasdoorClientIdKey, merchantIdKey, merchantWxAppIdKey)
	return ret, err
}

func (m *defaultMerchantModel) Update(ctx context.Context, newData *Merchant) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	merchantCasdoorClientIdKey := fmt.Sprintf("%s%v", cacheMerchantCasdoorClientIdPrefix, data.CasdoorClientId)
	merchantIdKey := fmt.Sprintf("%s%v", cacheMerchantIdPrefix, data.Id)
	merchantWxAppIdKey := fmt.Sprintf("%s%v", cacheMerchantWxAppIdPrefix, data.WxAppId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, merchantRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.Status, newData.CasdoorEndpoint, newData.CasdoorClientId, newData.CasdoorClientSecretEnc, newData.CasdoorOrg, newData.CasdoorApp, newData.CasdoorCertPem, newData.WxAppId, newData.WxAppSecretEnc, newData.Id)
	}, merchantCasdoorClientIdKey, merchantIdKey, merchantWxAppIdKey)
	return err
}

func (m *defaultMerchantModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheMerchantIdPrefix, primary)
}

func (m *defaultMerchantModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMerchantModel) tableName() string {
	return m.table
}
