// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"mall/service/user/rpc/internal/logic"
	"mall/service/user/rpc/internal/svc"
	"mall/service/user/rpc/types/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Login(ctx context.Context, in *user.LoginRequest) (*user.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) Register(ctx context.Context, in *user.RegisterRequest) (*user.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) UserInfo(ctx context.Context, in *user.UserInfoRequest) (*user.UserInfoResponse, error) {
	l := logic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}

func (s *UserServer) LoginByCasdoor(ctx context.Context, in *user.LoginByCasdoorRequest) (*user.LoginByCasdoorResponse, error) {
	l := logic.NewLoginByCasdoorLogic(ctx, s.svcCtx)
	return l.LoginByCasdoor(in)
}

func (s *UserServer) GetMerchant(ctx context.Context, in *user.GetMerchantRequest) (*user.GetMerchantResponse, error) {
	l := logic.NewGetMerchantLogic(ctx, s.svcCtx)
	return l.GetMerchant(in)
}
