// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type OrderAggregateRequest struct {
	Id int64 `json:"id"`
}

type OrderAggregateResponse struct {
	Order   OrderDetailResponse   `json:"order"`
	User    UserInfoResponse      `json:"user"`
	Product ProductDetailResponse `json:"product"`
}

type OrderDetailResponse struct {
	Id     int64 `json:"id"`
	Uid    int64 `json:"uid"`
	Pid    int64 `json:"pid"`
	Amount int64 `json:"amount"`
	Status int64 `json:"status"`
}

type ProductDetailResponse struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Desc   string `json:"desc"`
	Stock  int64  `json:"stock"`
	Amount int64  `json:"amount"`
	Status int64  `json:"status"`
}

type UserInfoResponse struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Gender int64  `json:"gender"`
	Mobile string `json:"mobile"`
}

type UserLoginRequest struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type UserLoginResponse struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}
