// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type OrderAggregateRequest struct {
	Id int64 `json:"id"`
}

type OrderAggregateResponse struct {
	Order   OrderDetailResponse   `json:"order"`
	User    UserInfoResponse      `json:"user"`
	Product ProductDetailResponse `json:"product"`
}

type OrderDetailResponse struct {
	Id     int64 `json:"id"`
	Uid    int64 `json:"uid"`
	Pid    int64 `json:"pid"`
	Amount int64 `json:"amount"`
	Status int64 `json:"status"`
}

type ProductDetailResponse struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Desc   string `json:"desc"`
	Stock  int64  `json:"stock"`
	Amount int64  `json:"amount"`
	Status int64  `json:"status"`
}

type UserInfoResponse struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Gender int64  `json:"gender"`
	Mobile string `json:"mobile"`
}

type UserLoginRequest struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type UserLoginResponse struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type MpLoginRequest struct {
	// MerchantId 商户 Id（SaaS 租户标识，必填；对应 merchant 表）
	MerchantId int64  `json:"merchantId"`
	Code       string `json:"code"`
	Username   string `json:"username,optional"`
	Avatar     string `json:"avatar,optional"`
	// PhoneCode getPhoneNumber 组件返回的一次性 code，用于换取手机号（必填）
	PhoneCode string `json:"phoneCode,optional"`
}

type MpLoginResponse struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	UserId       int64  `json:"userId"`
	// MerchantId 所属商户（租户）
	MerchantId int64 `json:"merchantId"`
	// CasdoorId Casdoor 用户 Id（稳定唯一关联键）
	CasdoorId string `json:"casdoorId"`
	// CasdoorName Casdoor 用户名（展示用）
	CasdoorName string `json:"casdoorName"`
	// Mobile 微信授权获取的真实手机号
	Mobile string `json:"mobile,omitempty"`
}
