// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type OrderCreateRequest struct {
	Uid    int64 `json:"uid"`
	Pid    int64 `json:"pid"`
	Amount int64 `json:"amount"`
	Status int64 `json:"status"`
}

type OrderCreateResponse struct {
	Id int64 `json:"id"`
}

type OrderDetailRequest struct {
	Id int64 `json:"id"`
}

type OrderDetailResponse struct {
	Id     int64 `json:"id"`
	Uid    int64 `json:"uid"`
	Pid    int64 `json:"pid"`
	Amount int64 `json:"amount"`
	Status int64 `json:"status"`
}

type OrderListRequest struct {
	Uid int64 `json:"uid"`
}

type OrderListResponse struct {
	Data []OrderDetailResponse `json:"data"`
}

type OrderRemoveRequest struct {
	Id int64 `json:"id"`
}

type OrderRemoveResponse struct {
}

type OrderUpdateRequest struct {
	Id     int64 `json:"id"`
	Uid    int64 `json:"uid,optional"`
	Pid    int64 `json:"pid,optional"`
	Amount int64 `json:"amount,optional"`
	Status int64 `json:"status,optional"`
}

type OrderUpdateResponse struct {
}

type PayCallbackRequest struct {
	Id     int64 `json:"id"`
	Uid    int64 `json:"uid"`
	Oid    int64 `json:"oid"`
	Amount int64 `json:"amount"`
	Source int64 `json:"source"`
	Status int64 `json:"status"`
}

type PayCallbackResponse struct {
}

type PayCreateRequest struct {
	Uid    int64 `json:"uid"`
	Oid    int64 `json:"oid"`
	Amount int64 `json:"amount"`
}

type PayCreateResponse struct {
	Id int64 `json:"id"`
}

type PayDetailRequest struct {
	Id int64 `json:"id"`
}

type PayDetailResponse struct {
	Id     int64 `json:"id"`
	Uid    int64 `json:"uid"`
	Oid    int64 `json:"oid"`
	Amount int64 `json:"amount"`
	Source int64 `json:"source"`
	Status int64 `json:"status"`
}

type ProductCreateRequest struct {
	Name   string `json:"name"`
	Desc   string `json:"desc"`
	Stock  int64  `json:"stock"`
	Amount int64  `json:"amount"`
	Status int64  `json:"status"`
}

type ProductCreateResponse struct {
	Id int64 `json:"id"`
}

type ProductDetailRequest struct {
	Id int64 `json:"id"`
}

type ProductDetailResponse struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Desc   string `json:"desc"`
	Stock  int64  `json:"stock"`
	Amount int64  `json:"amount"`
	Status int64  `json:"status"`
}

type ProductRemoveRequest struct {
	Id int64 `json:"id"`
}

type ProductRemoveResponse struct {
}

type ProductUpdateRequest struct {
	Id     int64  `json:"id"`
	Name   string `json:"name,optional"`
	Desc   string `json:"desc,optional"`
	Stock  int64  `json:"stock"`
	Amount int64  `json:"amount,optional"`
	Status int64  `json:"status,optional"`
}

type ProductUpdateResponse struct {
}

type UserInfoResponse struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Gender int64  `json:"gender"`
	Mobile string `json:"mobile"`
}

type UserLoginRequest struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type UserLoginResponse struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type UserRegisterRequest struct {
	Name     string `json:"name"`
	Gender   int64  `json:"gender"`
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type UserRegisterResponse struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Gender int64  `json:"gender"`
	Mobile string `json:"mobile"`
}
